import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import AuthProvider from "@/Provider/AuthProvider";
import { UserDataProvider } from "@/Provider/UserDataProvider";
import { Toaster } from "sonner";
import QueryProvider from "@/components/QueryProvider";
import ThemeInitializer from "@/components/ThemeInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TechFynite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <AuthProvider>
            <UserDataProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem={false}
                disableTransitionOnChange
                storageKey="theme"
                themes={["light", "dark"]}
                forcedTheme={undefined}
              >
                <ThemeInitializer />
                <Toaster richColors position="top-right" />
                {children}
              </ThemeProvider>
            </UserDataProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
